name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"    # every midnight
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: behnamasadi
          outputs: |
            output/snake.svg
            output/snake-dark.svg

      - name: Upload artifact (new v4)
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: output/snake.svg

      - name: Commit and push updated snake
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/snake.svg output/snake-dark.svg || true
          git commit -m "Update snake animation" || exit 0
          git push
