name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"      # runs every midnight
  workflow_dispatch:          # allows manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: behnamasadi        # change to your GitHub username
          outputs: |
            output/snake.svg
            output/snake-dark.svg

      - name: Upload to repo
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: output/snake.svg

      - name: Push to output branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "chore: update snake animation" || echo "No changes"
          git push
